import { S3Client } from "@aws-sdk/client-s3";

/**
 * SECURITY NOTES:
 * - In production (ECS/EC2/Lambda), do NOT set AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY at all.
 *   Attach an IAM Role to the compute resource instead — the SDK picks up credentials
 *   automatically via the container/instance metadata service. This avoids long-lived
 *   secrets ever touching your codebase or .env files.
 * - Local dev only: use a named AWS CLI profile or short-lived credentials from
 *   `aws sts assume-role`, never a root account's access keys.
 * - The bucket itself must have "Block all public access" ON. Files are only ever
 *   reached through short-lived presigned URLs generated by this backend.
 */
export const s3 = new S3Client({
  region: process.env.AWS_REGION || "ap-south-1",
  // Only set explicit credentials if provided (local dev). In prod, leave undefined
  // so the SDK's default credential provider chain uses the IAM role.
  ...(process.env.AWS_ACCESS_KEY_ID
    ? {
        credentials: {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY as string,
        },
      }
    : {}),
});

export const S3_BUCKET = process.env.AWS_S3_BUCKET as string;

// Whitelist of allowed MIME types — blocks executables, scripts, etc.
export const ALLOWED_MIME_TYPES = [
  "image/png",
  "image/jpeg",
  "image/webp",
  "image/gif",
  "application/pdf",
  "text/plain",
  "text/csv",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/zip",
];

export const MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024; // 10 MB
